### PR TITLE
Support TxSession.rollback() in Session.runTx().

### LINKED ISSUE #249: Migration for PostgreSQLExecutionContext.cancelTransaction()?
In the old version, I used this:

```
await connection.runTx((ctx) async {
   //...Do Stuff
   if(condition){
     ctx.cancelTransaction();
   }
}
```

With the new version, I found no cancelTransaction method for Session. So how to migrate it (Or: how to cancel a transaction based on a condition)?

### PR DESCRIPTION
**Pull request by isoos**
- Fixes #249.

### CODE REVIEW

**Comment by isoos** [comment]
/cc @simolus3
I've found the v2's `cancelTransaction` way to long, and it is not really cancel, rather `rollback`. It may also look better if/when we support multi-level transactions.

**Comment by simolus3** [comment]
I agree that `cancel` may be a confusing term for this. But to me, `rollback` makes it sound like the transaction will be rolled back right away, with subsequent operations being forbidden. It could be implemented like that by calling `_sendAndMarkClosed('ROLLBACK')`, and `runTx` itself only running the finalizing statement if `!transaction._sessionClosed` is true.
But if we want to allow queries after `rollback` in the transaction, I agree with the name and the implementation.

**Comment by isoos** [comment]
The problem here is the typed return value of `runTx`. We could do a `rollback(T value) => throw _RollbackException(value)`, and that way shortcut the callback method, or just let it run as is now. Maybe in the later case `markRollback()` would more appropriate?

**Comment by simolus3** [comment]
What I wanted to suggest is that `rollback()` should, without throwing an exception itself, prevent subsequent statements to run on the transaction. So when I do something like

```dart
runTx((tx) async {
  await tx.execute('update ....');
  await tx.rollback();
  await tx.execute('insert into ...'); // <- bad
});
```

We could make the `execute` after the rollback fail, essentially forcing `rollback` to be the last operation in a transaction callback. `rollback` itself doesn't have to throw or shortcut the callback method.

But I think keeping the current behavior and naming it `markRollback` is appropriate as well.

**Comment by isoos** [comment]
Implemented the suggestion above: `rollback()` actually sends the `ROLLBACK;` query and closes the session. Added test to check that later executions fail.

**Pull request merged**
