### PR TITLE
Force close connection (pool implementation)

### PR DESCRIPTION
**Pull request by davidmartos96**
Continuation of #396

### CODE REVIEW

**Comment by isoos** [comment]
Note: I think before considering this, we should revisit the regular connection's `close(force: true)`. I have found that I have troubles with the test if instead ignoring, I want to assert the output of `runLongQuery(conn)`. Not sure what's going on there, but it feels like we should do better.

**Comment by davidmartos96** [comment]
@isoos What kind of assert where you thinking about?

**Comment by isoos** [comment]
https://github.com/isoos/postgresql-dart/blob/master/test/v3_close_test.dart#L105

it should be:
```dart
await expectLater(rs, throwsA(isA<PgException>()));
```

I've added an exception to the result stream, and it kind of works, but for some reason that eludes me, the rs does throw, but the test still fails. Not sure why.

**Comment by davidmartos96** [comment]
> https://github.com/isoos/postgresql-dart/blob/master/test/v3_close_test.dart#L105
> 
> it should be:
> ```dart
> await expectLater(rs, throwsA(isA<PgException>()));
> ```
> 
> I've added an exception to the result stream, and it kind of works, but for some reason that eludes me, the rs does throw, but the test still fails. Not sure why.

Could it be a top level unhandled exception? I remember I had to do a <future>.ignore() to one of the long running because of that. Because no one would be listening the result of the future

**Comment by isoos** [comment]
Closing this in favor of #405.

**Pull request closed without merging**
