### PR TITLE
add support for interval

### PR DESCRIPTION
**Pull request by lslv1243**
Very good lib!
I added support for interval type to make it better, I hope it helps others.
Interval is represented as Duration in dart.

### CODE REVIEW

**Comment by isoos** [comment]
This looks great! Could you please also add:
- a test for inserting and querying (may amend an existing one, although they tend to be too large to follow in the argument lists)
- changelog entry in a similar format than the others?

**Comment by lslv1243** [comment]
@isoos Do I create a new version for the changelog?

**Comment by isoos** [comment]
> Do I create a new version for the changelog?

yes, please do! e.g. `2.4.1` would be I think the appropriate, as there is no new dependency or major change

**Comment by lslv1243** [comment]
@isoos I don't know how to run the tests locally, can you check if my tests are correct?

**Comment by isoos** [comment]
I've run the CI tests and this is the failure there: `PostgreSQLSeverity.error 08P01: insufficient data left in message`

You can create a local docker image similar to this specification to run the tests:
https://github.com/isoos/postgresql-dart/blob/master/.github/workflows/dart.yml#L19-L24

**Comment by lslv1243** [comment]
@isoos I can make it work by increasing the size of the ByteData to 16 instead of 8 when encoding (to match https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat). But when I write I only set the first 8 bytes (`bd.setInt64(0, value.inMicroseconds);`). 
Do you know what could be the next 8 bytes?

**Comment by isoos** [comment]
Looks like the interval can store  -178000000 years - 178000000 years in postgres in 16 bytes:
https://www.postgresql.org/docs/13/datatype-datetime.html

Let's increase the buffer size to 16, that's one step closer to the correct solution. However, I think we should also handle the second 8 bytes (or throw exception if it is non-null in parsing the value, and also at encoding, if it is negative interval or larger than 8 bytes).

**Comment by lslv1243** [comment]
@isoos What do you think of the implementation now? It do can handle negative values, I don't know what would go in the second part. 
I am throwing not implemented when decoding. I don't think there is something to be done when encoding since the dart int type has 64 bits size which matches the limit.

**Comment by isoos** [comment]
I've found a relevant discussion in the a Go postgresql driver: https://github.com/lib/pq/issues/78

I think I'll try to read a few other implementators code, but if nothing comes up in the next few hours, I'll merge this as-is, and publish it soon after. Maybe an additional test case with very large negative duration would be more reassuring, but this looks good to me.

**Comment by isoos** [comment]
perfect test, let's publish this! :)

**Comment by isoos** [comment]
2.4.1 is published, thanks for the contribution!

**Pull request merged**
