### PR TITLE
Add support for int8 array

### PR DESCRIPTION
**Pull request by schultek**
For reference: https://github.com/schultek/stormberry/issues/50

### CODE REVIEW

**Comment by isoos** [comment]
Thanks! This looks okay to me. Please also bump the version and add a changelog entry (referencing the PR and author as previous examples show it).

/cc @simolus3 any concerns here?

**Comment by schultek** [comment]
@isoos Done

**Comment by simolus3** [comment]
Thanks for the ping, I have no concerns about this :+1:

**Review by isoos — APPROVED** [review]

**Comment by isoos** [comment]
Published as 2.6.1

**Pull request merged**
