### PR TITLE
export PostgresTextEncoder

### PR DESCRIPTION
**Pull request by schultek**
Can we do this please? I need to use the `.convert()` method directly in my project.

### CODE REVIEW

**Comment by isoos** [comment]
@schultek: Can you please shed some light on the use case?

**Comment by schultek** [comment]
Sure. I need to build a rather complex sql query as a string. The generation of the query string is distributed across multiple classes and methods up to a point, where it is simply not feasible anymore to use `substitutionValues` in the `.query` call at the very end. So I need a way to properly encode my values in the query. 
Currently I have my own text encoding function, but I was realizing that I shouldn't need to do this since it already exists.

**Comment by schultek** [comment]
Wait I just was totally stupid. I just can directly do `import 'package:postgres/src/text_codec.dart';` 🙄

**Comment by schultek** [comment]
Sorry for bothering you. 😅✌️

**Comment by isoos** [comment]
No worries, however, this may be still a good idea to export, although not as part of the `postgres.dart` library, maybe as another `query_builder.dart` or similar lib. Another thing to consider: this is a single-method class, which could be a top-level method instead.

So, if you are still interested, I'd happily consider it as part of a library as a top-level method (which internally could just create an instance and call convert on it).

**Pull request closed without merging**
