### PR TITLE
Return SqlNull when TypeRegistry is configured for it.

### PR DESCRIPTION
**Pull request by isoos**
#322

### CODE REVIEW

**Comment by isoos** [comment]
/cc @davidmartos96 @simolus3 

Note: I think this is a very opinionated setting, and I don't see it as a default anytime soon. However, this way, it can have a decent exposure, and if there is a consensus, a later breaking version (4.0 or 5.0) may adapt it as default.

**Comment by davidmartos96** [comment]
LGTM
Happy to see the TypeRegistry class made this change quite trivial and non breaking.

**Review by simolus3 — COMMENTED** [review]
I agree that something needs to be done about this, but what worries me about the global option is that it will be hard for users to determine whether this option breaks any of the libraries they depend on which may also use the postgres package.

An alternative may be to report this by adding the information to the `ResultRow` class. We could continue mapping both kind of nulls to Dart's `null` but add a `isSqlNull(columnIndex)` method to provide a way to distinguish them?

**Comment by isoos** [comment]
@simolus3: fair points, it feels like a better (also non-breaking) change. I think I'll do another implementation with that.

**Pull request closed without merging**
