### PR TITLE
feat: Collect coverage and upload to codecov.io

### PR DESCRIPTION
**Pull request by eseidel**
Updated the GitHub Action to collect coverage information and upload to codecov.io

I also fixed the checkout action to use v3 since there was a warning due to a deprecated node runtime.

Once this lands it's easy to add a badge to the repo, but that will have to be done by the maintainer
since it will carry a token from codecov.

This is all free since this is open source.  The badge and tracking are nice.

### CODE REVIEW

**Review by isoos — APPROVED** [review]

**Comment by eseidel** [comment]
🎉 

You may have to add a CODECOV_TOKEN to the action secrets (the action results will tell you).

You also probably want to add the fancy badge (when you log in to codecov.io with your github they will generate you a link with a badge under the "settings" for the repo if you like).

Also the warning above says something about installing the app. 🤷 

Looking forward to driving this up with you all.

**Comment by eseidel** [comment]
https://app.codecov.io/gh/isoos/postgresql-dart is the link btw.

**Comment by isoos** [comment]
> You also probably want to add the fancy badge (when you log in to codecov.io with your github they will generate you a link with a badge under the "settings" for the repo if you like).

Tbh. I don't really like to authorize third-parties to act on my github account or see what I have access to (I have a few private repository where the owner would mind it). If you or somebody wants to share their account, I can give access to this repository though .. (I should do that for regular contributors anyway).

**Comment by eseidel** [comment]
Understandable, and totally understood.  I'm happy to have access if that's useful to you.  I think CodeCov works w/o any access to your github though too. 🤷   Really not trying to shill codecov so much as make it easier for casuals like myself to see the coverage data (which btw, is excellent, impressive job you've done testing).

**Pull request merged**
