### PR TITLE
Proposal: custom type encoding/decoding

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by isoos** [comment]
/cc @simolus3 @osaxma @radzish @hurrba

I'm looking for comments on every part of this: the names, the settings location, how this should work (e.g. is decoding to work based on oids, can it be synchronous or should it rather be `FutureOr`?), and whether this makes sense at all....

**Review by simolus3 — COMMENTED** [review]
I'm skeptical about this. It looks like there are two use cases this is addressing:

1. Types currently unsupported by this package.
2. Types correctly reported by this package, but users preferring something else (e.g. returning timestamps as string values).

For 1., this feels like admitting defeat when we should probably encourage these types to be added to this package instead. And 2. sounds, to me, like something that should be done by another package or the user. For instance, I maintain the higher-level `drift` package which supports type converters, and the lower-level `sqlite3` package for which (I think) something like type converters are out of scope. But of course I don't maintain this package and if the community feels different then that's fine :)

Perhaps, instead of integrating custom encodings that deep, we could just expose the underlying representation we got from postgres to clients? I like the addition of `typeOid` in `ResultSchemaColumn`, values returned by queries could have something like a `Uint8List | String` field storing the uninterpreted value we got from Postgres. To encode values, we could have say a `CustomType` class responsible for determining its postgres type name and oid as well as mapping to strings or blobs. That enables the same things, but without having to carry over a list of custom encoders everywhere.

**Comment by isoos** [comment]
For simple types, I agree with you, this package should handle that. I'm undecided on types like geospatial types in postgis though, and for custom postgresql types it is unlikely we want to handle them (https://www.postgresql.org/docs/current/sql-createtype.html).

I agree, one can always use the generic `Type.byteArray` + custom encoding of their type for encoding, and we could expose the raw values for decoding too...

I'll add the exposure of the `typeOid` separately. Not yet sure about the `Uint8List | String` yet, but will try to play with that too.

What do you mean by `CustomType`?

**Comment by simolus3** [comment]
Essentially, something that would give us a common interface for users to inject their own types with their own encoding.

Something like

```dart
execute(r'UPDATE foo SET bar = $1', parameters: [CustomType(oid: 1234, binary: Uint8List(...), text: '...')])
```

(well, likely not with that exact interface, but as a class to bundle it all up). If we have this to go from the direction towards Postgres and we expose the oid/raw data for the other way, we can avoid the custom converters internally and keep using the existing logic.

**Comment by isoos** [comment]
Closing in favor of #227 and further planned changes.

**Pull request closed without merging**
