### PR TITLE
added const for settings classes

### PR DESCRIPTION
**Pull request by Gerrel**
or else prevents me from making const repository classes

### CODE REVIEW

**Comment by isoos** [comment]
@Gerrel: I think also the `PoolSettings` should be set `const` to keep it consistent. Would you be also able to update the version and add a changelog entry?

**Comment by isoos** [comment]
@Gerrel: Thanks for the changes. How urgent this is for you to get it published?

**Comment by Gerrel** [comment]
@isoos Take your time ... there is no urgency.

**Comment by isoos** [comment]
published

**Pull request merged**
