### PR TITLE
Fixed double/real + added timestamp, numeric, date & json

### PR DESCRIPTION
**Pull request by pst9354**
Attempt to add some missing comversions in PostgresTextDecoder.
Also corrected conversion for double & real.

Created after discussion about: [PostgresTextDecoder](https://github.com/isoos/postgresql-dart/issues/337)

### CODE REVIEW

**Comment by isoos** [comment]
@pst9354: This is a great start! Could you please address the analysis error (Dead code.) and lints?

Would it be a stretching goal to also add some tests for these decodings, e.g. a few `SELECT x::CAST` queries with simple query protocol that check on the values?

Also: could you add a note to the changelog and bump the version?

**Comment by pst9354** [comment]
@isoos I don't see any analysis errors:
image

As everyone else, I'm really short of time :-) But I will try to find some time during the weekend...

**Comment by pst9354** [comment]
I just commited some changes.
Hope it's correct...

**Comment by isoos** [comment]
Added some tests + fixed a few things to match the tests. I don't have the time to implement `interval` right now, but added a placeholder test for it too. If you are happy with the current state, I'll merge and publish a new version.

**Comment by pst9354** [comment]
I think you actually broke some conversions, let me have a look tomorrow,

**Comment by isoos** [comment]
> I think you actually broke some conversions, let me have a look tomorrow,

If you change the test's queryMode to extended, it should return the same values, although on a different protocol. Understandable `interval` fails there, and otherwise only two of the DateTimes are different (only by the `Z` at the end - unsure if it is a bug in the simple or in the extended protocol).

**Comment by pst9354** [comment]
Yes, the Z at the end of DateTime is important.

We want to get the same results, using either the extended or simple protocol.
With your changes thay differ.

**Example:**
`SELECT '{\"color\": \"black\", \"size\": [\"S\",\"M\",\"L\",\"XL\"]}'::jsonb,1,now()::timestamp without time zone,now()::date,'TEST', 3::double precision, interval '5 hours',14.4::numeric;`

**Extended:**
[[{size: [S, M, L, XL], color: black}, 1, 2024-05-18 06:19:36.491719Z, 2024-05-18 00:00:00.000Z, TEST, 3.0, 18000000000 microseconds, 14.4]]

**Simple (your version):**
[[{size: [S, M, L, XL], color: black}, 1, 2024-05-18 06:19:56.719728, 2024-05-18 00:00:00.000, TEST, 3.0, Instance of 'UndecodedBytes', 14.4]]

**Simple (the version I commited, I only reverted the timestamp and date types):**
[[{size: [S, M, L, XL], color: black}, 1, 2024-05-18 06:28:35.579774Z, 2024-05-18 00:00:00.000Z, TEST, 3.0, Instance of 'UndecodedBytes', 14.4]]

**Comment by pst9354** [comment]
I just pushed the changes needed to get same results in extended and simple protocol.

(We are not using hre interval or numeric types in any of our projects, so I really don't know what types they are supposed to return)

**Comment by isoos** [comment]
I've tried to read more about this, and it is not clear to me what is being sent on the binary protocol, when somebody uses a timestamp without timezone. Filed https://github.com/isoos/postgresql-dart/issues/339 for further tracking of this issue, for the time being, I've opted to follow the binary protocol's values.

However, I updated your commit, as appending the `Z` marker seems to be fragile: the server may return the string value in different formats, where the `Z` postfix may not make sense, and in such case the entire parsing fails. With the current code it has a chance that `DateTime.parse` may still recognize it.

**Comment by isoos** [comment]
published, thank you!

**Comment by pst9354** [comment]
Great, my test-case works with the latest commit.

**Pull request merged**
