### PR TITLE
Support tsvector.

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by isoos** [comment]
Also: planning to implement `tsquery` support as well in a follow-up PR.

**Comment by simolus3** [comment]
Nice, I didn't even know Postgres has builtin support for those. Perhaps the `TsVector`, `Lexeme` and `LexemeWeight` classes should have a small documentation comment pointing towards https://www.postgresql.org/docs/current/datatype-textsearch.html so that it's easier to know what they're used for.

**Comment by isoos** [comment]
It is really neat, not ElasticSearch-level, but provides an acceptable search experience. I've used previously it via creating the string object being transformed in the postgres server, and now I want to have it as a typed interface.

**Pull request merged**
