### PR TITLE
Autodetect type from parameter value.

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by isoos** [comment]
@simolus3: could you please review if this is the correct place and mode to infer types?
it fixes 2 out of the 11 failing adapted-tests from `query_test.dart`

**Comment by isoos** [comment]
apparently the `variable_tokenizer_test.dart` expects this autodetection to not happen (or happen elsewhere)...

**Review by simolus3 — APPROVED** [review]
I think inferring types based on values is a good fallback, and this seems like the right way  to do it.

Regarding the failing test, I think we can just remove the expectation in line 31 of `variable_tokenizer_test.dart`. It essentially asserts that we're not providing a fallback, but I don't really see how that's useful.

**Comment by isoos** [comment]
@simolus3: An interesting issue which I don't know how to attack yet:
https://github.com/isoos/postgresql-dart/blob/master/test/query_test.dart#L430-L441
this test gets autodetected `(int2, 0)` as parameter, but postgres expects a string-like value at that column, so instead of the expected issue with the non-nullable column, we get an exception with `insufficient data left in message`

**Comment by isoos** [comment]
^ possibly ignore the above question, I may have mixed two stack traces and lost context from one into the other...

**Comment by simolus3** [comment]
I think the problem is that we're setting a `null` type in the `Parse` message, so Postgres expects a text representation in the `Bind` message. I'll investigate further and try to come up with a solution.

**Pull request merged**
