### PR TITLE
Refactoring Type

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by isoos** [comment]
/cc @simolus3 there is a lot of going on here, but the gist is: `Type` now becomes a class, allowing a later support for user-provided type encoding/decoding. To aim that, there is a separate `TypeRegistry` that is now global/static, but could become Connection-level (although it may be just fine to keep it static).

wdyt of this direction?

**Comment by simolus3** [comment]
This looks useful, and I think apart from `TupleDataColumn.typeName` the migration to custom type registries seems doable.

An advantage of enums is that, when adding a new value, we can get automatic compile errors for builtin type handling (e.g. in the encoders and decoders). Have you considered whether a type layout like this could work as well?

```dart
sealed class Type<T extends Object> {
  String get nameForSubstitution;
  // ...  

  Uint8List? encodeAsBytes(Object? value, Encoding encoding);
  Object? decodeFromBytes(
      Uint8List? value, Encoding encoding, bool isBinaryEncoding);
}

interface class CustomType<T extends Object> implements Type<T> { }

enum BuiltinType<T extends Object> implements Type<T> {
  // existing definition
}
```

The encoder could then have a switch statement like this and get its exhaustiveness checked statically:

```dart
switch (type) {
  // existing enums
  CustomType() => type.encodeAsBytes(...)
}
```

But maybe the complexity from that is not worth the benefit.

**Comment by isoos** [comment]
> An advantage of enums is that, when adding a new value, we can get automatic compile errors for builtin type handling (e.g. in the encoders and decoders).

The thing that I am considering here is to create a separate class for each type that the package handles, e.g. `Int4Type`, `Int8Type`, where both could inherit the text-based parts from an abstract `IntType`... That way the encode and decode is at the same place, their code, the review and testing of it is simpler. These may not be public classes, but only internal to the package...

Similar to what you have suggested, but instead of the enum, I'd break up the the binary and text encoder and decoders. Not necessarily blocking it on the 3.0 release, so I think that can happen later, I just want to get the API in a good position for it. wdyt?

**Comment by simolus3** [comment]
That sounds even better :+1:

**Comment by isoos** [comment]
This got really big but seems like a useful direction. Some notes:

Using `EncodeInput` and `DecodeInput` allows us to expand the parameters if later it gets needed by the user-provided custom types, without breaking the API much.

I'm undecided about the `EncodedOutput` class, it could be just an `Object` instead and we could enforce `String or Uint8List` internally.

I'll remove the `Type.name_` property in a separate PR, callers should use the `toString()` method for debug purposes and these types should provide the information needed for that.

**Pull request merged**
