### PR TITLE
Remove obsolete files.

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by eseidel** [comment]
Will look tonight!

**Comment by eseidel** [comment]
This commit looks fine.  I suspect it's some other reason, looking.

**Comment by eseidel** [comment]
I see recent commits:
https://app.codecov.io/gh/isoos/postgresql-dart/commits

**Comment by eseidel** [comment]
Ah, actions shows the error:
https://github.com/isoos/postgresql-dart/actions/runs/6553047483/job/17797629240
```
Codecov report uploader 0.6.3
[2023-10-17T[21](https://github.com/isoos/postgresql-dart/actions/runs/6553047483/job/17797629240#step:10:22):35:57.133Z] ['info'] => Project root located at: /home/runner/work/postgresql-dart/postgresql-dart
[2023-10-17T21:35:57.135Z] ['info'] -> No token specified or token is empty
[2023-10-17T21:35:57.148Z] ['info'] Searching for coverage files...
[2023-10-17T21:35:57.253Z] ['info'] Warning: Some files located via search were excluded from upload.
[2023-10-17T21:35:57.254Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2023-10-17T21:35:57.255Z] ['info'] => Found 1 possible coverage files:
  coverage.lcov
[2023-10-17T21:35:57.255Z] ['info'] Processing /home/runner/work/postgresql-dart/postgresql-dart/coverage.lcov...
[2023-10-17T21:35:57.261Z] ['info'] Detected GitHub Actions as the CI provider.
[2023-10-17T21:35:57.665Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.4-uploader-0.6.3&token=*******&branch=master&build=6553047483&build_url=https%3A%2F%2Fgithub.com%2Fisoos%2Fpostgresql-dart%2Factions%2Fruns%2F6553047483%2Fjob%2F17797629240&commit=a68351a3fdf9ca5246000eab32ea7459af2f6a[22](https://github.com/isoos/postgresql-dart/actions/runs/6553047483/job/17797629240#step:10:23)&job=Dart&pr=&service=github-actions&slug=isoos%2Fpostgresql-dart&name=&tag=&flags=&parent=
[20[23](https://github.com/isoos/postgresql-dart/actions/runs/6553047483/job/17797629240#step:10:24)-10-17T21:35:57.943Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

**Comment by eseidel** [comment]
https://github.com/codecov/codecov-action/issues/837 seems to claim that the problem is that without a token the upload gets rate-limited sometimes.

**Comment by eseidel** [comment]
The token would show up for you here:
https://app.codecov.io/gh/isoos/postgresql-dart/settings

**Comment by isoos** [comment]
Thanks for looking into this! I may create a separate account to get the access shared with codecov...

**Comment by eseidel** [comment]
I'm not sure what OAuth scopes they use (I'm sure you know OAuth better than I do given its use in pub), but I suspect CodeCov only sees your email as part of their use of GitHub OAuth, just as a way to see that you own this repo an thus are allowed to see the token for it.  That said, it's not at all clear to me that CodeCov upload tokens need to be kept secret for public repositories.  Their docs are unclear:
https://docs.codecov.com/docs/frequently-asked-questions#where-is-the-repository-upload-token-found

**Comment by isoos** [comment]
If it were read-only and public-repositories-only, I wouldn't mind it, but IIRC they asked full access to all my repositories. Anyway, account separation is not that bad thing to do...

**Pull request merged**
